// Code generated by goctl. DO NOT EDIT.
package types

type UploadReq struct {
	Dir            string `form:"dir,optional"`
	FileNameCreate int8   `form:"fileNameCreate,optional"`
}

type UploadResp struct {
	Url      string `json:"url"`
	FileName string `json:"fileName"`
}
