// Code generated by goctl. DO NOT EDIT.
package types

type UploadReq struct {
	Dir string `form:"dir,optional"`
}

type UploadResp struct {
	Url      string `json:"url"`
	FileName string `json:"fileName"`
}
