// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	file "filestorage/oss/internal/handler/file"
	"filestorage/oss/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.TokenMiddleware, serverCtx.CorsMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/upload",
					Handler: file.UploadHandler(serverCtx),
				},
			}...,
		),
	)
}
